#!bin/bash
# This script takes care of the setup for turning on a Vagrant cluster so I don't have to
# type the same thing over and over, haha.

# Create a cluster according to the config files.
vagrant up

# Delete the old known hosts so that we don't run into SSH errors.
rm /Users/David/.fleetctl/known_hosts
touch /Users/David/.fleetctl/known_hosts

# Give the cluster your public key
vagrant ssh-config | sed -n "s/IdentityFile//gp" | xargs ssh-add
