#!bin/bash/
#===============================================================================
# CoreOS - Reflector Demo
#===============================================================================

# This script is part of the CoreOS + Docker tutorial from PandaStrike.  It
# stops the "reflector" service and resets the CoreOS machine.


#==================
# Fleet
#==================
# Stop the reflector service.
fleetctl stop reflector.service

# Destroy the reflector service.
fleetctl destroy reflector.service


#==================
# Docker
#==================
# Stop all Docker containers
docker kill $(docker ps -a -q)

# Delete all Docker containers
docker rm $(docker ps -a -q)

# Delete all Docker images
docker rmi $(docker images -q)
